### PR TITLE
Update next-js.mdx with correct bunx installation command.

### PR DESCRIPTION
**Pull request by adityabrahmankar**
Fixed the bunx create next-app command.

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content
- Changes to the docs site code
- Something else!

#### Description

- Closes # 
- What does this PR change? Give us a brief description. 
- Did you change something visual? A before/after screenshot can be helpful.

### CODE REVIEW

**Comment by vasfvitor** [comment]
Hi, thanks for catching this, but Next.js docs says it is the way current it is `create-next-app`. I haven't tested https://nextjs.org/docs/pages/api-reference/create-next-app so maybe it's outdated?
image

If you have tested it to be different, let me know so I can reopen this and test myself. Then we can open a issue upstream to make sure it's not just a typo

**Comment by adityabrahmankar** [comment]
image

bun create next-app is the correct way which works as shown in the official bun documentation.

**Comment by FabianLars** [comment]
It has to be bun create instead of bunx create then though, right? Since bunx is an alias for bun x (the binary run command) I assume it will cause issues? I don't have bun installed / I'm not home so I can't test this rn

**Review by vasfvitor — APPROVED** [review]
Here what I get on windows, fresh bun out of the oven:
`bunx create-next-app --use-bun` error
`bunx create next-app --use-bun` works
same with `bun`

Oddly, yesteday, on next.js changed the docs to the current non working case
https://www.github.com/vercel/next.js/pull/64151

On bun cli it states it should be not dashed https://github.com/oven-sh/bun/blob/main/src/cli.zig#L1669

In a quick test, I noticed that `bunx create whatever-app` is an alias to `create-wahatver-app`, so `bunx create tauri-app` works to as `create-tauri-app`.

Again, thanks for bringing this up and citing the source docs which I should have looked at myself.

**Review by dreyfus92 — APPROVED** [review]
Thanks everyone, LGTM ✅

**Pull request merged**
