### PR TITLE
docs: fix command to create next app using bun

### PR DESCRIPTION
**Pull request by zeybek**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- Changes to the docs site code

#### Description
- What does this PR change? Give us a brief description.
  It will fix typo in command to create next app with bun 
- Did you change something visual?
  No

### CODE REVIEW

**Review by vasfvitor — CHANGES_REQUESTED** [review]
Hi this was recently changed in https://github.com/tauri-apps/tauri-docs/pull/2041, did bun changed the command again? Could you share where/when they changed, and, if any, announcement?

`bunx create next-app --use-bun` Still works for me. 

https://bun.sh/guides/ecosystem/nextjs

**Comment by zeybek** [comment]
> Hi this was recently changed in #2041, did bun changed the command again? Could you share where/when they changed, and, if any, announcement?
> 
> `bunx create next-app --use-bun` Still works for me.
> 
> https://bun.sh/guides/ecosystem/nextjs

hi @vasfvitor, I'm currently using `bun@1.1.4` and existing command for `bun` is not working, to make it work we can use one of the following commands
- `bun create next-app`
- `bunx create-next-app`

**Comment by vasfvitor** [comment]
image
image

**Comment by vasfvitor** [comment]
if this is a platform difference (I'm on Windows) please share the source where we can verify this to be the case

**Comment by zeybek** [comment]
@vasfvitor I'm on `MacBook Pro M1` and `Sonoma 14.3.1` has been installed, also as we can see on NextJS official documentation, command has been given as `bunx create-next-app`, please check [here](https://nextjs.org/docs/app/api-reference/create-next-app) and [here](https://bun.sh/docs/cli/bun-create#from-npm)

Btw, it is weird that you can run `bunx` with `create next-app` since it is equivalent of `npx`

**Comment by dreyfus92** [comment]
> if this is a platform difference (I'm on Windows) please share the source where we can verify this to be the case

It might be a platform thing I've tested both and the new command works me, the older doesn't. Also note I'm as well on macOS 😁

**Comment by simonhyll** [comment]
image

image

No screenshot for Mac but I tried it on my work Sonoma 14.1 Mac and the results are the same.

The existing one works, `bun create next-app --use-bun`, the proposed one doesn't. Closing.

**Pull request closed without merging**
