### PR TITLE
feat: switch to `meilisearch-docsearch`

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

**Comment by lorenzolewis** [comment]
Put a comment in Discord, but on the component footer how about saying "Powered by" instead of "Search by" since we want to make sure we don't try to represent Meilisearch ourselves

**Comment by amrbashir** [comment]
Should be good to go now

**Review by FabianLars — APPROVED** [review]

**Comment by amrbashir** [comment]
alright, that was hopefully the last bug and last version today

**Comment by lorenzolewis** [comment]
Don't hate me, but one visual "glitch". Can the sizes of the magnifying glass and the spinner where the query being performed be set to the same width? They jump around when you're typing (at least on Safari) 

https://user-images.githubusercontent.com/15347255/217293513-0c1f16c3-476b-4f6e-ba88-523cbdb8a9dd.mov

**Comment by amrbashir** [comment]
done!

**Comment by lorenzolewis** [comment]
Perfect! Ready to merge?

**Comment by amrbashir** [comment]
if the glitch is gone, then yes!

**Pull request merged**
