### PR TITLE
docs: add Neovim debugging instructions

### PR DESCRIPTION
**Pull request by kandrelczyk**
This PR contains additional debugger setup instructions for Neovim.

### CODE REVIEW

**Comment by ahkohd** [comment]
looks good to me!

**Review by dreyfus92 — APPROVED** [review]
Thank you @ahkohd for reviewing this and thank you @kandrelczyk for taking the time in contributing. Welcome @kandrelczyk to `tauri-docs` 🫡

**Comment by dreyfus92** [comment]
@kandrelczyk to fix the ci/cd issue you just gotta `pnpm format` on your terminal and after that just run a sanity check `pnpm format:check` to fix the issue.

**Comment by kandrelczyk** [comment]
@dreyfus92 fixed the formatting

**Comment by dreyfus92** [comment]
Thanks again @kandrelczyk 🫡

**Pull request merged**
