### PR TITLE
i18n(zh-cn): translate `distribute/dmg.mdx`

### PR DESCRIPTION
**Pull request by GuoJikun**
#### Description

- What does this PR change? Give us a brief description. 
- Closes #

### CODE REVIEW

**Review by vasfvitor — APPROVED** [review]
'reviewed' with translation, rapidly compared the original and translated back to english. Seems fine. Do you think this is a valid way to check. On one hand I don't want this sitting here, but I don't want to unknowingly merge typos

**Comment by GuoJikun** [comment]
> 'reviewed' with translation, rapidly compared the original and translated back to english. Seems fine. Do you think this is a valid way to check. On one hand I don't want this sitting here, but I don't want to unknowingly merge typos通过翻译进行“审阅”，快速比较原文并翻译回英文。看起来不错。您认为这是一种有效的检查方法吗？一方面，我不想让它坐在这里，但我不想在不知不觉中合并错别字

It sounds good.
'English -> Chinese -> English' is very common in this process because of translation inconsistencie(I'm not sure that's an accurate description).

**Comment by vasfvitor** [comment]
oh I just remembered once I read through a guide to write Chinese copy, and I it mentioned full width characters. And it seems 
you used them correctly. I'll try to find it again and use as a reference to common typos and mistakes

edit: found it english version: https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md

**Comment by GuoJikun** [comment]
There is a chinese version: https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md

[vue's Chinese documentation](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E5%8D%8F%E4%BD%9C%E6%8C%87%E5%8D%97) is almost the best of all Chinese translations.

**Pull request merged**
