### PR TITLE
add authme lite to the showcase

### PR DESCRIPTION
**Pull request by Levminer**
* Adding Authme Lite to the showcase

### CODE REVIEW

**Comment by nothingismagick** [comment]
Looks fine to me, but with this proficiency you may want to update your skills:

image

**Review by nothingismagick — APPROVED** [review]

**Comment by Levminer** [comment]
> Looks fine to me, but with this proficiency you may want to update your skills:
> 
> image

Thank you, but I only used tauri so far to maximize the window and open a link so I don't know much about it yet, but I like it so far.

**Comment by Laegel** [comment]
Thanks for the PR @Levminer ! :smile:

**Comment by Levminer** [comment]
> Thanks for the PR @Levminer ! 😄

Thank you for the very fast response and merge!

**Pull request merged**
