### PR TITLE
Added Mail-Dev to showcase.

### PR DESCRIPTION
**Pull request by samirdjelal**
Added Mail-Dev to showcase.

### CODE REVIEW

**Comment by Laegel** [comment]
Hey @samirdjelal , thanks for the PR!
Do you have an icon to add?

**Comment by samirdjelal** [comment]
> Hey @samirdjelal , thanks for the PR!
> Do you have an icon to add?

I've used this icon, I've no idea why it doesn't appear in the website!
https://github.com/tauri-apps/tauri-docs/pull/260/files

and here is the icons from the repo
https://github.com/samirdjelal/mail-dev/tree/main/src-tauri/icons

**Comment by Laegel** [comment]
Your file is called "icon" when the queried image is called "logo". :wink:

**Comment by samirdjelal** [comment]
That was embarrassing lol
I was reading it and still not getting why it is not found!

**Pull request merged**
