### PR TITLE
[i18nIgnore] fix: Fix link error.

### PR DESCRIPTION
**Pull request by GuoJikun**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

Fix link error in http page.

### CODE REVIEW

**Review by vasfvitor — APPROVED** [review]
Hey nice catch! Would you mind checking the docs if there are any more instances the links are outdated in this same pattern? I wonder if it's possible to use relative links, instead of full urls.

If not, lemme know so I can merge this already. Thanks

**Comment by GuoJikun** [comment]
> Hey nice catch! Would you mind checking the docs if there are any more instances the links are outdated in this same pattern? I wonder if it's possible to use relative links, instead of full urls.
> 
> If not, lemme know so I can merge this already. Thanks

I will try.

**Comment by GuoJikun** [comment]
An error occurs when running 'pnpm build' with the following message.

```bash
[CouldNotTransformImage] Could not transform image `/_astro/diagram.ByZzOWqU.svg`. See the stack trace for more information.
  Hint:
    This is often caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
  Error reference:
    https://docs.astro.build/en/reference/errors/could-not-transform-image/
  Stack trace:
    at generateImageInternal (file:///E:/private/Web/tauri-docs/node_modules/.pnpm/astro@4.5.16/node_modules/astro/dist/assets/build/generate.js:131:21)
    at async file:///E:/private/Web/tauri-docs/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36
  Caused by:
  Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (file:///E:/private/Web/tauri-docs/dist/chunks/astro/assets-service_Xes6Nu_7.mjs:321:11)
    at async generateImageInternal (file:///E:/private/Web/tauri-docs/node_modules/.pnpm/astro@4.5.16/node_modules/astro/dist/assets/build/generate.js:125:26)
    at async file:///E:/private/Web/tauri-docs/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36
```
@vasfvitor

**Comment by GuoJikun** [comment]
The build speed of the documentation is a bit long

**Comment by vasfvitor** [comment]
> The build speed of the documentation is a bit long

yeah, we have to find a way so /releases pages to build only on production and doesn't break build on prs

**Comment by vasfvitor** [comment]
> An error occurs when running 'pnpm build' with the following message.

This is odd as sharp is already on the repo

**Comment by GuoJikun** [comment]
> > An error occurs when running 'pnpm build' with the following message.
> 
> This is odd as sharp is already on the repo

Yes, I see "sharp" in `package.json`

**Comment by GuoJikun** [comment]
> > The build speed of the documentation is a bit long
> 
> yeah, we have to find a way so /releases pages to build only on production and doesn't break build on prs

Generate it once when you release a new release and cache the generated pages in a separate directory, so that you only need to copy the cached directory into the final build each time you merge your PR.

**Comment by GuoJikun** [comment]
> I wonder if it's possible to use relative links, instead of full urls.

This is done.

**Comment by vasfvitor** [comment]
> Generate it once when you release a new release and cache the generated pages in a separate directory, so that you only need to copy the cached directory into the final build each time you merge your PR.

I guess this wouldn't work as the bulk of time are from Astro build step; We can't cache the final html because I'm mostly sure that the bundled css and js will have different hashes. Btw, for images this is possible and already in use for [astro-og-canvas](https://github.com/delucis/astro-og-canvas/tree/latest/packages/astro-og-canvas). 

The Astro team have been studying a way to [implement incremental builds](https://github.com/withastro/roadmap/blob/incremental-builds/proposals/0044-incremental-build.md). Our solution should be as simples as "if production build, if not don't"

**Comment by vasfvitor** [comment]
> This is done.

Thanks!

**Comment by GuoJikun** [comment]
> > Generate it once when you release a new release and cache the generated pages in a separate directory, so that you only need to copy the cached directory into the final build each time you merge your PR.
> 
> I guess this wouldn't work as the bulk of time are from Astro build step; We can't cache the final html because I'm mostly sure that the bundled css and js will have different hashes. Btw, for images this is possible and already in use for [astro-og-canvas](https://github.com/delucis/astro-og-canvas/tree/latest/packages/astro-og-canvas).
> 
> The Astro team have been studying a way to [implement incremental builds](https://github.com/withastro/roadmap/blob/incremental-builds/proposals/0044-incremental-build.md). Our solution should be as simples as "if production build, if not don't"

Cache the contents below.

image

**Comment by vasfvitor** [comment]
I think those are so quick to generate that doesn't impact that much

**Pull request merged**
