### PR TITLE
Fixes for non-main ref in translation status page

### PR DESCRIPTION
**Pull request by lorenzolewis**
@dklassic would you be able to test the contributing page now to make sure all the links work as expected? We won't really be able to test the "Translations that need reviews" section until we cross that path, but I think this should resolve all the broken links I hit yesterday during the call.

Might still be a few weird things around CI, but I'll fix that separately because it won't impact the i18n flow

### CODE REVIEW

**Comment by lorenzolewis** [comment]
(kicks Netlify's CI): here's the rendered dashboard btw: https://deploy-preview-1374--tauri-docs-starlight.netlify.app/contribute/translate-status

**Comment by FabianLars** [comment]
ngl that dashboard is fancy af

**Comment by dklassic** [comment]
> @dklassic would you be able to test the contributing page now to make sure all the links work as expected? We won't really be able to test the "Translations that need reviews" section until we cross that path, but I think this should resolve all the broken links I hit yesterday during the call.
> 
> Might still be a few weird things around CI, but I'll fix that separately because it won't impact the i18n flow

All links from Contribution Page seems fine, but I believe "Edit page" on individual pages still isn't referenced properly, not sure if you're fixing it with this pr as well. If not, than all seems fine :)

**Review by dklassic — APPROVED** [review]
nvm didn't notice the issue title. All seems to be working, let's goooo

**Comment by lorenzolewis** [comment]
> ngl that dashboard is fancy af

That's why I "borrowed" it ;) I've been thinking about asking if they want that turned into an official package/integration upstream, but I feel like they might not because it's for a very specific i18n flow.

**Comment by lorenzolewis** [comment]
Fixed the edit link, thanks for jogging my memory @dklassic 😅

**Pull request merged**
