### PR TITLE
setup-windows: add instructions for Webview2 debugging

### PR DESCRIPTION
**Pull request by nklayman**
As per convo in Discord:
https://discordapp.com/channels/616186924390023171/625037620996734986/765094262416343060

### CODE REVIEW

**Comment by nklayman** [comment]
Darn the links don't work.

**Comment by nklayman** [comment]
Poor netlify having to rebuild the site a million times because I keep screwing stuff up 🤣.

**Comment by nklayman** [comment]
Okay a million and a half commits later and I think it's good lol.

**Comment by nklayman** [comment]
That's what I get for doing it all in github instead of testing locally.

**Comment by Laegel** [comment]
It's okay with the commits @nklayman , we're squashing anyway. Thanks to you and @AmrBinBashir for the initial PR. :)

**Pull request merged**
