### PR TITLE
feat: Migrates `i18ntracker` to `Lunaria`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

- What does this PR change? Give us a brief description. 
Migrates `i18ntracker` package to use `lunaria` as default. This will offload maintenance of the `i18ntracker` and enhance a bit more the the current state of the tracker's UI.
> [!NOTE]
> Encountered an issue where Lunaria couldn't track the git history of certain files used in generating Tauri documentation. This is due to these files being fetched via a git submodule, which isn't reflected in the project's main git history.
> 
> Implemented a temporary fix in the Lunaria config to bypass this issue:
> 
> ``` json
> "ignore": [
>   "src/content/docs/references/{v1,v2}/(js/**/*|config).{md,mdx}"
> ]
> ```
> This change prevents Lunaria from tracking these files, thus avoiding the error. We'll explore a more permanent solution that maintains the necessary git history for seamless documentation generation in the future.
- Did you change something visual? A before/after screenshot can be helpful.

| Before | After |
| ------ | ----- |
| Before | After |

### CODE REVIEW

**Review by vasfvitor — CHANGES_REQUESTED** [review]
What about the "Translations that need reviews" section missing?
PR:
https://deploy-preview-1854--tauri-docs-starlight.netlify.app/contribute/translate-status/ 
Broken anchor: "[existing Tauri Docs PRs](https://deploy-preview-1854--tauri-docs-starlight.netlify.app/contribute/translate-status/#needs-review)"

Current:
https://beta.tauri.app/contribute/translate-status

Other than that LGTM!

**Comment by GuoJikun** [comment]
Are there any new developments? The current i18n page display is incomplete. 
I gave it a try in a local environment. Screenshot below

af

**Comment by dreyfus92** [comment]
@GuoJikun, we're still waiting to handle most of the missing docs and current structure to handle this one.

**Comment by dreyfus92** [comment]
Gonna close this to migrate it to the new version of the docs.

**Pull request closed without merging**
