### PR TITLE
Adding Flatpak Documentation

### PR DESCRIPTION
**Pull request by RoseBlume**
#### Description

- What does this PR change? Give us a brief description. 
1. The guide makes it look like the app is built locally and the bundle is updated, however in order to get onto flathub you are required to have remote sources.
2. Metainfo is required on flathub, as such I have added a metainfo file to the manifest example.
3. I demonstrated architecture specific sources.
4. I added local instructions to submit to flathub.

### CODE REVIEW

**Comment by RoseBlume** [comment]
Ok that should be good.

**Comment by thewh1teagle** [comment]
Where do we need to place metainfo.xml file? does the name matters? I tried to set it in the same folder where I execute `flatpak-builder` but it doesn't copy it to build folder and it throws error

**Comment by RoseBlume** [comment]
Can you please send me the link to your project. Typically it should be upstream and then installed to the metainfo folder as shown. Can you please also send me the error? It may be a linter error regarding the quality of the metainfo. @thewh1teagle

**Comment by RoseBlume** [comment]
> Where do we need to place metainfo.xml file? does the name matters? I tried to set it in the same folder where I execute `flatpak-builder` but it doesn't copy it to build folder and it throws error

Whats the error?

**Comment by thewh1teagle** [comment]
> Can you please send me the link to your project. Typically it should be upstream and then installed to the metainfo folder as shown. Can you please also send me the error? It may be a linter error regarding the quality of the metainfo. @thewh1teagle

Sure, I just pushed it into new branch `feat/flatpak`
https://github.com/thewh1teagle/vibe/tree/feat/flatpak



> Whats the error?

```console
  flatpak git:(feat/flatpak) flatpak-builder --repo vibe --force-clean build-dir github.com.thewh1teagle.vibe.yml 
Emptying app dir 'build-dir'
Downloading sources
Starting build of github.com.thewh1teagle.vibe
Cache miss, checking out last cache hit
========================================================================
Building module binary in /home/user/Documents/vibe/desktop/src-tauri/flatpak/.flatpak-builder/build/binary-20
========================================================================
Running: ar -x *.deb
Running: tar -xf data.tar.gz
Running: install -Dm755 usr/bin/vibe /app/bin/vibe
Running: install -Dm644 usr/share/applications/vibe.desktop /app/share/applications/github.com.thewh1teagle.vibe.desktop
Running: install -Dm644 usr/share/icons/hicolor/128x128/apps/vibe.png /app/share/icons/hicolor/128x128/apps/github.com.thewh1teagle.vibe.png
Running: install -Dm644 usr/share/icons/hicolor/32x32/apps/vibe.png /app/share/icons/hicolor/32x32/apps/github.com.thewh1teagle.vibe.png
Running: install -Dm644 usr/share/icons/hicolor/256x256@2/apps/vibe.png /app/share/icons/hicolor/256x256@2/apps/github.com.thewh1teagle.vibe.png
Running: install -Dm644 github.com.thewh1teagle.metainfo.xml /app/share/metainfo/github.com.thewh1teagle.vibe.metainfo.xml
install: cannot stat 'github.com.thewh1teagle.metainfo.xml': No such file or directory
Error: module binary: Child process exited with code 1
```

**Comment by RoseBlume** [comment]
Double check the name. 

> > Can you please send me the link to your project. Typically it should be upstream and then installed to the metainfo folder as shown. Can you please also send me the error? It may be a linter error regarding the quality of the metainfo. @thewh1teagle
> 
> Sure, I just pushed it into new branch `feat/flatpak` https://github.com/thewh1teagle/vibe/tree/feat/flatpak
> 
> > Whats the error?
> 
> ```
>   flatpak git:(feat/flatpak) flatpak-builder --repo vibe --force-clean build-dir github.com.thewh1teagle.vibe.yml 
> Emptying app dir 'build-dir'
> Downloading sources
> Starting build of github.com.thewh1teagle.vibe
> Cache miss, checking out last cache hit
> ========================================================================
> Building module binary in /home/user/Documents/vibe/desktop/src-tauri/flatpak/.flatpak-builder/build/binary-20
> ========================================================================
> Running: ar -x *.deb
> Running: tar -xf data.tar.gz
> Running: install -Dm755 usr/bin/vibe /app/bin/vibe
> Running: install -Dm644 usr/share/applications/vibe.desktop /app/share/applications/github.com.thewh1teagle.vibe.desktop
> Running: install -Dm644 usr/share/icons/hicolor/128x128/apps/vibe.png /app/share/icons/hicolor/128x128/apps/github.com.thewh1teagle.vibe.png
> Running: install -Dm644 usr/share/icons/hicolor/32x32/apps/vibe.png /app/share/icons/hicolor/32x32/apps/github.com.thewh1teagle.vibe.png
> Running: install -Dm644 usr/share/icons/hicolor/256x256@2/apps/vibe.png /app/share/icons/hicolor/256x256@2/apps/github.com.thewh1teagle.vibe.png
> Running: install -Dm644 github.com.thewh1teagle.metainfo.xml /app/share/metainfo/github.com.thewh1teagle.vibe.metainfo.xml
> install: cannot stat 'github.com.thewh1teagle.metainfo.xml': No such file or directory
> Error: module binary: Child process exited with code 1
> ```

Did you add the metainfo file to your sources? If not then it won't work. If it is included in the debian bundle please ensure that the install command is pointing to the correct directory

**Pull request closed without merging**
