### PR TITLE
Add quick and dirty mobile dev workflow

### LINKED ISSUE #1024: [docs] How to launch app on mobile?
Hi everyone!

Thank you so much for your project, and I'm particularly interested in the mobile version.
I've followed the instructions to create the base project (vanilla version), then followed the ["next" documentation](https://next--tauri.netlify.app/next/mobile/).

However, there is no word on how to launch on Android and / or iOS.
Could you add it to the docs (and maybe write it also in this issue).

### PR DESCRIPTION
**Pull request by crapStone**
closes #1024

### CODE REVIEW

**Comment by lucasfernog** [comment]
Any chance I can have push access to your branch? :D

**Comment by crapStone** [comment]
because this is a organization I had to invite you :sweat_smile:

**Comment by lucasfernog** [comment]
Thank you!! :heart:

**Comment by crapStone** [comment]
Now it's not quick and dirty anymore :D

**Comment by lucasfernog** [comment]
Really?? I don't think I've changed it that much :joy:

**Comment by crapStone** [comment]
You explained it much better than I did and added missing links.

**Comment by lucasfernog** [comment]
Maybe we should move this to be the first section in the sidebar?

**Comment by crapStone** [comment]
If you are new to tauri mobile development I think it's better to first change your application and then learn how the tauri subcommands work. That way you can go straight through the documentation by clicking on the next button on the bottom of each page.

**Review by lucasfernog — APPROVED** [review]

**Comment by crapStone** [comment]
is something missing?

**Comment by FabianLars** [comment]
whoops sorry, didn't see that lucas approved it.

**Pull request merged**
