### PR TITLE
fix(translate-status): error link to github address to `zh-cn`

### PR DESCRIPTION
**Pull request by RSS1102**
#### Description

- What does this PR change? Give us a brief description. 
image

image

image

### CODE REVIEW

**Review by vasfvitor — APPROVED** [review]
Tested navigation on a few pages and everything seems to be working fine. So is the tracker now. Thanks

**Comment by vasfvitor** [comment]
why the 'confused' emoji?

**Comment by RSS1102** [comment]
> Contributor

sorry，I thought you were referring to a normal production environment, just now....

**Review by vasfvitor — CHANGES_REQUESTED** [review]
~my bad. It doesn't work, tested on the wrong tracker url~ ... it was right

**Pull request merged**
