### PR TITLE
Add Next.js Framework Guide

### PR DESCRIPTION
**Pull request by knownasnaffy**
This will add a setup guide for using Nextjs framework as a frontend tool with Tauri app. It follows the `nextjs-ts` template in the `create-tauri-app`. Some instructions have been copied from [Pull#838](https://github.com/tauri-apps/tauri-docs/pull/838) by @leon3s

### CODE REVIEW

**Comment by knownasnaffy** [comment]
The update-docs workflow is failing, is there a fault in my code?

**Comment by FabianLars** [comment]
Don't worry about it, it's failing because of an issue in the tauri repo

**Comment by knownasnaffy** [comment]
@FabianLars Thanks for the reply

**Comment by lorenzolewis** [comment]
Thanks for this! I'm going to close this out in favour of #838 that we just merged. In general we also try to keep these guides very minimal (no CSS for instance) so that we can let the reader focus on just the bits specific to Tauri. 

Thanks again! <3

**Pull request closed without merging**
