### PR TITLE
Instructions regarding app signing

### PR DESCRIPTION
**Pull request by AdrianVispalia**
App signing is essential in order to upload an app to the play store.

In this commit I add specific instructions on how to use  Java key store to sign the AAB file.

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks for contributing! We probably will wait until https://github.com/tauri-apps/tauri/pull/9964 lands as the instructions will change then.

**Review by simonhyll — CHANGES_REQUESTED** [review]
Just gonna block the merge based on the upstream issue needing to be resolved :)

**Comment by FabianLars** [comment]
9964 was closed but from the discussions emerged another signing guide: https://github.com/tauri-apps/tauri-docs/pull/2337 - it does not mention the play store though so i'd be open for suggestions on how to approach this (maybe just close this PR too and have the play store docs focus more on the rest of the publishing process)

**Comment by tweidinger** [comment]
Implemented by Lucas in #2588 and #2579

**Pull request closed without merging**
