### PR TITLE
Feat/i18n

### PR DESCRIPTION
**Pull request by lorenzolewis**
Now ready to turn on the fancy i18n (insert random emoji here).

**Note:** This is currently not going to upload any of the files in the `docs` folder; it will only be some default Docusaurus strings and anything in the `pages` folder that properly has the translation elements woven in. Additional docs will be enabled for translation in their respective PRs as I'd like to use this to only **enable** i18n, not necessarily populate everything at once.

Deploy logs of a dry-run test on this branch: https://app.netlify.com/sites/tauri/deploys/6299ef3b62286600082b039b

### CODE REVIEW

**Comment by lorenzolewis** [comment]
-- Don't merge --
Just testing the action

**Comment by lorenzolewis** [comment]
Here are the test deploy logs showing successful authentication and dry runs for crowding: https://app.netlify.com/sites/tauri/deploys/6299ef3b62286600082b039b

Going to change the netlify config to now only run this in the production context

**Comment by JonasKruckenberg** [comment]
Awesome! Do we want to merge it right or would that send the wrong message?

**Comment by FabianLars** [comment]
imo we should merge it relatively asap, but without advertising it (for now). Just so that we can make sure everything works

**Comment by lorenzolewis** [comment]
It's good to merge now.

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
