### PR TITLE
correct macOS 12. version

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
The webkit version actually didn't change since 12.5.1 🤷🏻‍♂️

### CODE REVIEW

**Comment by FabianLars** [comment]
@JonasKruckenberg 
The Safari version for macos 12.5.1 is wrong (i think)? What's `16.5.1` supposed to actually be? x)

**Comment by JonasKruckenberg** [comment]
Okay let me check that

**Comment by JonasKruckenberg** [comment]
Okay I just checked with a colleague, macOS 12.5.1 also has `613.3.9.1.16`

**Comment by FabianLars** [comment]
And that's Safari 15.6 right?

**Comment by JonasKruckenberg** [comment]
15.6.1 is what Safari reports on my coworkers machine, so I assume it's the same for 15.6

**Comment by FabianLars** [comment]
Ah alrighty, so it's just a Zahlendreher, thanks :v:

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
