### PR TITLE
SearchBar Component Cleanup

### PR DESCRIPTION
**Pull request by lorenzolewis**
Want to put this in place as a stop-gap to at least clear up a bit of logic while we continue looking into https://github.com/tauri-apps/tauri-docs/issues/372

### CODE REVIEW

**Comment by FabianLars** [comment]
it's alright overall, but it always shows a scrollbar (because of the image?)

**Comment by lorenzolewis** [comment]
Ah didn't notice that (dang hidden scrollbars), let me see...

**Comment by lorenzolewis** [comment]
They have some weird styling choices with that dependency... I love seeing how the dark theme input is wider than the light theme
Screenshot 2022-05-13 at 20 13 03
Screenshot 2022-05-13 at 20 12 58

**Review by FabianLars — APPROVED** [review]

**Comment by FabianLars** [comment]
yeah let's just not talk about it 😅

**Pull request merged**
