### PR TITLE
Feature/migrate to v2

### PR DESCRIPTION
**Pull request by Laegel**
Moving from Docusaurus v1 to v2. Still a lot to do before the docs are ready.

### CODE REVIEW

**Comment by nothingismagick** [comment]
3:13:24 PM: failed during stage 'building site': Deploy directory 'website/build/tauri' does not exist

**Comment by nothingismagick** [comment]
That is so beautiful. Love the netlify bot too. Wow!

**Comment by jbolda** [comment]
@nothingismagick the build directory is different per version. If we use the file configuration, it will override the "global" settings we have in netlify.

**Comment by nothingismagick** [comment]
I guess in the next step we'd need to fix that standard footer.

**Review by nothingismagick — APPROVED** [review]

**Comment by Laegel** [comment]
@nothingismagick Yeah, for now I've not changed the Docusaurus links placeholders, just wanted to have something "ready" first.

**Pull request merged**
