### PR TITLE
list yarn first and specify it is our own package manager for v1

### PR DESCRIPTION
**Pull request by chippers**
it's a bit disingenuous to list pnpm first and remove the yarn recommendation descriptions, especially since we use yarn for v1

### CODE REVIEW

**Comment by FabianLars** [comment]
It used to be "preferred by" and that wasn't true at all so we decided on discord to just remove it all together, because "both have their good/bads" (quote from lucas).
The re-ordering happened because the first idea was to show that pnpm is preferred by most of the (active) members now (still included the "preferred by" suffix). And ngl i was a fan of the alphabetical ordering too lol.

I can def live with your phrasing tho and honestly who the f cares so i'm just gonna merge it 🤷 

Edit: Nvm about the merge just yet. Do we want to mention that it's explicitly about yarn v1?

**Comment by chippers** [comment]
as-is it already explicitly mentions v1. the decision on discord was basically dont rock the boat for something that doesn't matter that much, which is why we stopped the pnpm PR

**Comment by FabianLars** [comment]
Yes it mentions tauri@v1 but not yarn@v1 and we link to the new yarn too so we really don't make any suggestions that we ~~don't like yarn berry at all~~ use yarn 1 exclusively.

**Comment by chippers** [comment]
> Yes it mentions tauri@v1 but not yarn@v1 and we link to the new yarn too so we really don't make any suggestions that we ~don't like yarn berry at all~ use yarn 1 exclusively.

i see what you mean

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
