### PR TITLE
Fix External link target, TAO/WRY caps, blog link

### PR DESCRIPTION
**Pull request by lorenzolewis**
CC @probablykasper

### CODE REVIEW

**Review by FabianLars — APPROVED** [review]
i hate the caps change btw but i guess it's the default

**Review by probablykasper — CHANGES_REQUESTED** [review]
Looks like it's still showing those "open in new tab" icons

**Comment by lorenzolewis** [comment]
Those I prefer to keep because it's at least a visual indicator that it's an external domain 🤷

**Comment by probablykasper** [comment]
hmm, I feel like it might be confusing, but feel free to keep it if you think that's best, or if someone else agrees

**Comment by amrbashir** [comment]
I agree to keep it, I really like the indicator for external sites (I think it is also good for accessibility), so I can use middle click instead of normal click.

**Comment by lorenzolewis** [comment]
@probablykasper is that alright? (would you like to begrudgingly click the approve button?) <3

**Review by probablykasper — COMMENTED** [review]
Yes 👍

**Review by probablykasper — APPROVED** [review]
Ok for real this time 🤦‍♂️

**Pull request merged**
