### PR TITLE
feat: expand tray guide

### PR DESCRIPTION
**Pull request by lucasfernog**
include JS API usage, and split the guide into steps for each API instead of a single huge example that is harder to digest

### CODE REVIEW

**Review by vasfvitor — APPROVED** [review]
there are a few \`\`\`\` instead of triple ticks \```. It isn't breaking the layout tho

**Comment by vasfvitor** [comment]
oh it was the formatting, then it's ok I guess

**Comment by vasfvitor** [comment]
nope, it's kinda broken
image

**Comment by vasfvitor** [comment]
I'm formatting

**Comment by lucasfernog** [comment]
thank you !!!

**Pull request merged**
