### PR TITLE
Document APPLE_PROVIDER_SHORT_NAME

### PR DESCRIPTION
**Pull request by swissmanu**
This adds documentation describing the changes of https://github.com/tauri-apps/tauri/pull/3289, fixing https://github.com/tauri-apps/tauri/issues/3288.

### CODE REVIEW

**Review by FabianLars — APPROVED** [review]

**Comment by FabianLars** [comment]
Thanks :heart: Gonna merge this once we have the release candidate ready.

**Comment by lucasfernog** [comment]
I just had to sign a macOS app at work, and I think I can improve the docs tonight.

**Comment by JonasKruckenberg** [comment]
I think with the work we're doing on the docs rn, you will have to recreate this PR (maybe even recreate it against the `v1` branch while you're at it so your contribution doesn't get lost)

**Comment by FabianLars** [comment]
@swissmanu We are done with the restructuring for now, so if you have the time we'd appreciate if you can recreate that change 🙏

**Comment by swissmanu** [comment]
Sure! I'll let you know 👍

**Comment by FabianLars** [comment]
superseded by #502

**Pull request closed without merging**
