### PR TITLE
feat(distribution): add windows guide

### PR DESCRIPTION
**Pull request by lucasfernog**

### CODE REVIEW

**Review by FabianLars — APPROVED** [review]

**Comment by lucasfernog** [comment]
No changes requested? Seems like I'm getting good at this :D

**Comment by FabianLars** [comment]
My only change request is for the bundler not the docs :P (offline evergreen installer in addition to the fixed version), but otherwise i can't spot anything 👍

**Comment by lucasfernog** [comment]
I tried that a while ago and completely failed to do it based on the examples.

**Comment by FabianLars** [comment]
Understandable, i didn't even understand the examples at all lol

**Pull request merged**
