### PR TITLE
Make the getting started page more welcoming.

### PR DESCRIPTION
**Pull request by adunkman**
We want people to feel comfortable diving in — leaving out statements which make presumptions about the reader’s intelligence can go a long way!

### CODE REVIEW

**Review by lucasfernog — APPROVED** [review]

**Comment by lucasfernog** [comment]
I like this change. What do you guys think @Laegel @nothingismagick

**Comment by Laegel** [comment]
Hey @adunkman , thanks for the issue. Would you please be a bit more explicit, provide details about what you think is wrong with the current approach?

**Comment by adunkman** [comment]
Sure! By using phrases like "obviously," folks who don’t find that information obvious may feel excluded, or that this product isn’t for them. It can just as easily be left out, to include those folks. 🙂

**Review by nothingismagick — APPROVED** [review]
LGTM - and I really appreciate your attention to detail! Thanks @adunkman

**Pull request merged**
