### PR TITLE
Feat/lottie-player Dependency

### PR DESCRIPTION
**Pull request by lorenzolewis**
Previously the JS for the Lottie animation on the index page had the raw player JS in the project. This removes that and instead relies on the NPM package for Lottie Player.

### CODE REVIEW

**Comment by FabianLars** [comment]
Side note: An automatic bundle size benchmark on PRs would be nice 😅

**Comment by FabianLars** [comment]
Hmmm, can we make it a little bit smaller again? Or do you prefer it that like this?

Oh and is it trivial to prevent the layout shift?

**Comment by lorenzolewis** [comment]
I want to remove Lottie completely for the v1.0 home page ideally

**Comment by FabianLars** [comment]
Okay then let's get this out of the way for now

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
