### PR TITLE
kickstart dynamic og images #1344

### PR DESCRIPTION
**Pull request by vasfvitor**
Kickstart dynamic og images generation based on reference provided in #1344 with minor fixes

This depends on startlight being updated to 0.11.0. So it sorta depends on #1601

This is not ready as some pages don't have `description` field in the frontmatter, but have `title`. In those cases it is returning **undefined** written on the OG image. Example: /features/commands/

Plus the current design is minimal 

preview:
commands
notification

### CODE REVIEW

**Comment by vasfvitor** [comment]
build fail could be related to [80452ee](https://github.com/tauri-apps/tauri-docs/pull/1608/commits/80452eee74098493396d612c91c9276f08d49fba) return modification

**Comment by lorenzolewis** [comment]
Hey @vasfvitor this is so awesome, thank you! I got #1601 merged in so this should be unblocked now. I took a few minutes to mock up a potential design for this based on our current direction if you'd like to take a stab at implementing it:

https://www.figma.com/file/ZgVWAeFQsLbFhUpuQ2kl17/Tauri.app-2.0?type=design&node-id=987%3A5394&mode=design&t=DbZoItgt9mEy7Myg-1

Open Graph Image_ Short

https://www.figma.com/file/ZgVWAeFQsLbFhUpuQ2kl17/Tauri.app-2.0?type=design&node-id=992%3A2233&mode=design&t=DbZoItgt9mEy7Myg-1

Open Graph Image_ Long

https://www.figma.com/file/ZgVWAeFQsLbFhUpuQ2kl17/Tauri.app-2.0?type=design&node-id=992%3A2255&mode=design&t=DbZoItgt9mEy7Myg-1

Open Graph Image_ Blog

I think we'll have two different types: 1 for pages, and another for a blog post. I've mocked up a design for each. Let's follow the reference for frontmatter for pages where `title` is required and `description` is optional (so we should be able to handle no description https://starlight.astro.build/reference/frontmatter/). Similar for blog posts but where `title` is required and `excerpt` is optional (https://github.com/HiDeoo/starlight-blog#frontmatter). I think it would also be good to include the date for a blog post

--- 

Open to feedback on any of this and thanks for getting this started! 💜

**Comment by vasfvitor** [comment]
git mishap, workin on it

**Comment by vasfvitor** [comment]
@lorenzolewis I made a mistake (synced with dev branch) but I solved now. I couldn't figure how to fix this pr showing the history from the 'dev' branch tho. I didn't intend to close the pr

Anyways... I'll start to work right away. Thanks for all the information and details

**Comment by lorenzolewis** [comment]
No worries, we've all been there 😅 Feel free to open another PR when you're ready and just mention this one in it so we have a reference back.

**Pull request closed without merging**
