### PR TITLE
doc: document `APPLE_PROVIDER_SHORT_NAME`

### PR DESCRIPTION
**Pull request by farfromrefug**
added a small description for `APPLE_PROVIDER_SHORT_NAME`

### CODE REVIEW

**Comment by FabianLars** [comment]
Can you add a small sentence or link that shows how to obtain the name (asking because #378 did that), i'm not a mac guy so if this is super obvious anyway i'm fine with not mentioning it.

Furthermore mentioning it in #Workflow modifications would be nice too imo (again #378).

**Comment by farfromrefug** [comment]
@FabianLars dumb me i did not see that other PR. Do you want me to update this PR with the changes from the other PR? Would that be enough?

**Comment by FabianLars** [comment]
~~The env var thing is good to copy-paste imo.~~
For the other thing i prefer your phrasing, so just append the link with a small sentence 👍

**Comment by farfromrefug** [comment]
@FabianLars is that good with you now?

**Comment by FabianLars** [comment]
Yes perfect, thanks ❤️

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
