### PR TITLE
adds debug-trainer to showcase

### PR DESCRIPTION
**Pull request by neurodynamic**
Just finished this app with Tauri and it was a really nice experience!

### CODE REVIEW

**Comment by nothingismagick** [comment]
This needs a description too. @Laegel - should we document this better?

**Comment by nothingismagick** [comment]
See this PR to see where to add it to the translations file:
https://github.com/tauri-apps/tauri-docs/pull/236/files

**Comment by Laegel** [comment]
I guess we should, yup. I think this issue will be solved when we move to Docusaurus builtin i18n system but as long as it's not done, it's going to happen.

**Comment by neurodynamic** [comment]
Just added. That work?

**Comment by nothingismagick** [comment]
Yep, that worked.

**Review by nothingismagick — APPROVED** [review]

**Comment by Laegel** [comment]
Thanks for your PR @neurodynamic , nice project BTW. :+1:

**Comment by neurodynamic** [comment]
@Laegel Thanks!! And no problem 🙂

**Pull request merged**
