### PR TITLE
Typo change in Next.js getting started docs

### PR DESCRIPTION
**Pull request by quiint**
#### Description

Typo change - bunx create next-app to bunx create-next-app
image

### CODE REVIEW

**Comment by FabianLars** [comment]
Why does everyone say something different 😭 https://github.com/tauri-apps/tauri-docs/pull/2041 / https://github.com/tauri-apps/tauri-docs/pull/2077

**Comment by quiint** [comment]
@FabianLars maybe it's on different operating systems? this is what it shows for my linux board:
image

the original issue came from my m1 mac running 1.0.36

**Comment by simonhyll** [comment]
If ran with `bunx` it should be `bunx create-next-app`. If ran with `bun` it should be `bun create next-app`. Anything else is a user side issue

What `bun` does is check in npmjs for a package called `create-next-app`, which is made available in a prettier way by doing `bun create next-app`. This is the same way all JS package managers handle the create functionality

What `bunx` does is the same as e.g. `npx`, which is download the specified package, in other words `create-next-app`, and runs it.

So if anybody raises more PR's regarding "fixing" this, don't merge anything other than what's actually correct. If they're able to run `bunx create next-app` it's something weird on their system, it's actively against the official patterns and intended usages.

**Review by simonhyll — APPROVED** [review]
Using `bunx` this updated version is indeed the correct syntax. If anyone says otherwise, they're wrong.

**Pull request merged**
