### PR TITLE
i18n(es): translation of quick start to spanish

### PR DESCRIPTION
**Pull request by jcasben**
This PR will contain all the changes to create and update the translations of the section Quick Start from the docs to Spanish.

Files created/changed:

- es/start/index.mdx (new)
- es/start/frontend/qwik.mdx (new)
- es/start/frontend/sveltekit.mdx (new)
- es/start/frontend/nuxt.mdx (update)
- es/start/frontend/trunk.mdx (update)
- es/start/frontend/nextjs.mdx (update)
- es/start/prerequisites.mdx (update)
- es/start/migrate/from-tauri-1.mdx (update)

### CODE REVIEW

**Comment by dreyfus92** [comment]
@jcasben feel free to ping on me on this one once you're done so I can take a look 😁

**Comment by jcasben** [comment]
@dreyfus92 I think that I'm done :)

**Review by dreyfus92 — APPROVED** [review]
Thank you @jcasben, LGTM ✅

**Comment by dreyfus92** [comment]
Woops, we're missing the proper format, to fix the ci/cd issue you just gotta `pnpm format` on your terminal and after that just run a sanity check `pnpm format:check` to fix the issue.

**Comment by jcasben** [comment]
I don't understand why, but when I run `pnpm format`, in the Spanish version of `qwik.mdx`, it changes the format in a way that produces the following error:

image

**Comment by jcasben** [comment]
I saw that this was also causing problems in the other languages, so I added qwik.mdx to prettierignore  as I so the that this was the solution proposed by others and now works fine

**Comment by dreyfus92** [comment]
Thanks again @jcasben 🫡

**Pull request merged**
