### PR TITLE
Update sponsors

### PR DESCRIPTION
**Pull request by ezekg**
Hey team! We sponsored Tauri back on Jan 5th and would love to get my company's logo added.

### CODE REVIEW

**Comment by lucasfernog** [comment]
Thanks for the PR! I didn't update it before because we are planning on a redesign of the sponsors page :)

**Comment by lucasfernog** [comment]
We should discuss a Tauri integration btw.

**Comment by ezekg** [comment]
I just saw the redesign-related stuff, so I figured as much. I went ahead and opened a PR since I couldn't find a working contact email. And yes, definitely — I'd love to get an integration figured out!

Feel free to ping me anytime and we can discuss.

**Comment by lorenzolewis** [comment]
I'll go ahead and merge this one in (any UI changes will have these types of updates rolled into them).

For the contact email, which one did you try? Would always be a good idea to have that up and running 😄

**Comment by lorenzolewis** [comment]
Tagging @nothingismagick here

**Comment by ezekg** [comment]
Sweet. I tried contact@tauri.studio, but I got a bounce email back saying:

```
User doesn't exist: khionu@tauri.studio
```

**Comment by lorenzolewis** [comment]
I'll bring it up with the team and we'll get that fixed/updated, thanks!

**Pull request merged**
