### PR TITLE
Add Guix setup instructions

### PR DESCRIPTION
**Pull request by declantsien**
This PR add Tauri development environment setup instructions using [Gnu Guix](https://en.wikipedia.org/wiki/GNU_Guix).

GNU Guix is a functional cross-platform package manager and a tool to instantiate and manage Unix-like operating systems, based on the Nix package manager. Configuration and package recipes are written in Guile Scheme.

Later we can proceed to distribute Tauri app on Guix..

### CODE REVIEW

**Comment by FabianLars** [comment]
Thank you for contributing!

Just so you know why there is a delay here: I am honestly a little indecisive about merging this. So far we tried to restrict it to only somewhat popular systems to not bloat the docs. I'd like to wait for the opinion on that from some more people :)
Maybe a tutorial/blog post (cross linked in the awesome-tauri repo) would be a cool alternative too in case we don't end up merging this,

**Comment by declantsien** [comment]
I realized that now Guix is a minority :sob: .

> Maybe a tutorial/blog post (cross linked in the awesome-tauri repo) would be a cool alternative too in case we don't end up merging this,

I'll see what I can do.

**Comment by phlummox** [comment]
Hi declantsien, out of interest, did you end up posting this anywhere else?

I ran into a few issues, and would be interested to learn further how you ended up building your project. Using the `manifest.scm` you suggested on an Ubuntu system with Guix installed, I got link errors along the lines of this:

```
  /usr/bin/ld: /gnu/store/dgm3k4vkyv2jg2ca1c4pclbh5ki4i7lf-fontconfig-minimal-2.13.94/lib/libfontconfig.so.1: undefined reference to `lstat@GLIBC_2.33'
```

(presumably because compilation is using the host version of `ld`, and it's having trouble finding the Guix version of libc, which differs from the host's version of 2.31).

That can be fixed by adding `"gcc-toolchain"` to the manifest, but ends up resulting in a segfault when trying to build the [`libc`](https://crates.io/crates/libc) crate (probably for the same reason).

So that means you need to include Guix's version of the Rust toolchain as well, by adding `"rust"` and `"rust:cargo"` to the manifest (and shifting any existing `~/.cargo` out of the way), at which point you run into [this bug](https://lists.gnu.org/archive/html/help-guix/2019-09/msg00003.html) which causes Cargo to fail when connecting to sites which use SSL...

On the whole, I think it would be easier at that point just to use Docker or Podman to get a reliable build environment; I think Guix hosted on another OS is probably fiddlier to use with Tauri than most people would want.

**Comment by declantsien** [comment]
phlummox ***@***.***> writes:

> Hi declantsien, out of interest, did you end up posting this anywhere
> else?

Nah, I didn't motivated enough to writing up something.

>
> I ran into a few issues, and would be interested to learn further how you ended up building your project. Using the `manifest.scm` you suggested on an Ubuntu system with Guix installed, I got link errors along the lines of this:
>
> ```
>   /usr/bin/ld: /gnu/store/dgm3k4vkyv2jg2ca1c4pclbh5ki4i7lf-fontconfig-minimal-2.13.94/lib/libfontconfig.so.1: undefined reference to ***@***.***_2.33'
> ```
>
> (presumably because compilation is using the host version of `ld`, and it's having trouble finding the Guix version of libc, which differs from the host's version of 2.31).
>
> That can be fixed by adding `"gcc-toolchain"` to the manifest, but ends up resulting in a segfault when trying to build the [`libc`](https://crates.io/crates/libc) crate (probably for the same reason).
>
> So that means you need to include Guix's version of the Rust toolchain as well, by adding `"rust"` and `"rust:cargo"` to the manifest (and shifting any existing `~/.cargo` out of the way), at which point you run into [this bug](https://lists.gnu.org/archive/html/help-guix/2019-09/msg00003.html) which causes Cargo to fail when connecting to sites which use SSL...
>
> On the whole, I think it would be easier at that point just to use Docker or Podman to get a reliable build environment; I think Guix hosted on another OS is probably fiddlier to use with Tauri than most people would want.
>

I don't know..., I didn't have these issues back then since I don't use
rustup on Guix.

For Rust development on Guix I have this in manifest.
...
	      "rust@nightly-2023-03-28:rust-docs"
	      "rust@nightly-2023-03-28:rust-docs-json-preview"
	      "rust@nightly-2023-03-28:clippy-preview"
	      "rust@nightly-2023-03-28:rust-analyzer-preview"
	      "rust@nightly-2023-03-28:rust-demangler-preview"
	      "rust@nightly-2023-03-28:rustfmt-preview"
...
You can find the package definition here[0].
Once thought to make something like rust-overlay[1] for Guix. But that
didn't happen.

[0]:
https://git.sr.ht/~declantsien/guix-channel/tree/master/item/binary/packages/rust.scm#L182
[1]: https://github.com/oxalica/rust-overlay

**Comment by phlummox** [comment]
No worries, thanks for the help!

I'll definitely try out the Rust manifest, but not for the current project I'm working on. It sounds like getting the Tauri `manifest.scm` to work on my system will likely require more time than I have available right now, so I will probably just use Docker instead. Cheers!

**Comment by declantsien** [comment]
phlummox ***@***.***> writes:

> It sounds like getting the Tauri `manifest.scm` to work on my system will likely require more time than I have available right now

Nah, it's just as easy as adding this channel to your
~/.config/guix/channels.scm, see[0].

(channel
        (name 'declantsien)
        (url "https://git.sr.ht/~declantsien/guix-channel")
        (branch "master")
        (commit
          "e6ae2599e19423a041510f93335c306bee329487")
        (introduction
          (make-channel-introduction
            "0c171cf43849f86516e1ee23aec34e586654a3a7"
            (openpgp-fingerprint
              "F695 F39E C625 E081 33B5  759F 0FC6 8703 75EF E2F5"))))

[0]: https://guix.gnu.org/manual/en/html_node/Using-a-Custom-Guix-Channel.html

**Comment by phlummox** [comment]
> Nah, it's just as easy as adding this channel to your
> ~/.config/guix/channels.scm, see[0].
> 
> (channel
>         (name 'declantsien)
>         (url "https://git.sr.ht/~declantsien/guix-channel")
>         (branch "master")
>         (commit
>           "e6ae2599e19423a041510f93335c306bee329487")
>         (introduction
>           (make-channel-introduction
>             "0c171cf43849f86516e1ee23aec34e586654a3a7"
>             (openpgp-fingerprint
>               "F695 F39E C625 E081 33B5  759F 0FC6 8703 75EF E2F5"))))

Perhaps it would have been worth putting that in your original pull request, if doing this is essential to getting things to work.

I should point out, though, that if someone doesn't *have* a .config/guix/channels.scm file - I didn't - then adding the above to it (after putting it in a `(list ...)` will result in an error like the following:

```
/home/user/.config/guix/channels.scm:2:4: error: 'guix' channel is lacking
hint: Make sure your list of channels contains one channel named `guix' providing the core of Guix.
```

No doubt there's a simple fix for this, too, but as I said, I don't have time to investigate it.

**Comment by declantsien** [comment]
> on an Ubuntu system with Guix installed

@phlummox 
My bad. Just read your previous post again. Didn't realize you are using Guix on a foreign distro(Ubuntu). 
Sorry about that.
I think you can just follow the Debian part from Tauri's [Setting Up Linux](https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux) section, as Ubuntu is a distro based on Debian, but again I am not sure. Or you can stick to your docker solution.

I am using the manifest.scm mentioned here on my [Guix System](https://distrowatch.com/table.php?distribution=guixsd), wonder why this didn't work for you. 
Also, just tested Rust 1.60.0 from [guix channel](https://git.savannah.gnu.org/git/guix.git), it works fine with Tauri. Since Tauri 1.2 only requires Rust 1.59 to compile.

**Review by lorenzolewis — APPROVED** [review]
I'm going to go ahead and merge this one in. In the future we'll have a Community Resources section on pages so @declantsien if you would like to make a fuller blog post or tutorial we'd be more than happy to add that in! 

Thanks for the PR 🙏

**Comment by Erudition** [comment]
Thanks for this! fellow Guix SD user here.

I too had to replace the `gcc` in the manifest with `gcc-toolchain` to get past the `gcc is superseded` warnings.
I had to add `node` to the manifest to build an app that uses js.
I had to run `export LD_LIBRARY_PATH=$LIBRARY_PATH` in the shell to get past the `node: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory` problem with node and npm.
I had to add `rust` to the manifest so that it can use rust if not installed on user's system already. In my case I had `rustc` already, but it was too old for one of the project's dependencies.
Another rust dependency complained about lack of OpenSSL, which I have yet to figure out.

**Pull request merged**
