### PR TITLE
Guide(Frontend): Add Qwik

### PR DESCRIPTION
**Pull request by vanvuongngo**
#### What kind of changes does this PR include?

- New content migrated from v1

#### Description

- Add guide how to use the qwik frontend

qwik

### CODE REVIEW

**Comment by simonhyll** [comment]
@vanvuongngo After the recent restructure we'll need this PR to reflect that change. Thanks!

**Comment by vanvuongngo** [comment]
Hi @simonhyll,

plz review

**Comment by vanvuongngo** [comment]
Can you help with a qwik starter option?
It would be nice when there is also a qwik option when I call this:
```sh
pnpm create tauri-app
```

**Comment by simonhyll** [comment]
> Hi @simonhyll,
> 
> plz review

On it 😄

**Review by simonhyll — APPROVED** [review]

**Comment by simonhyll** [comment]
LGTM, shipping it, thanks!! 🥳

**Pull request merged**
