### PR TITLE
Improve allowlist docs

### PR DESCRIPTION
**Pull request by matthme**
The allowlist documentation has been confusing for me so I extended it.
It is based on my current understanding of it and its correctness needs to be confirmed by people actually understanding it in case this PR is considered useful.

### CODE REVIEW

**Comment by FabianLars** [comment]
I really like this change. The only problem here is that it's auto generated from here https://github.com/tauri-apps/tauri/blob/dev/core/tauri-utils/src/config.rs#L2143 - i'd appreciate if you could open a PR against the main repo too 🙏

**Comment by FabianLars** [comment]
p.s. all commits must be signed for us to be able to merge them: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits - i _could_ merge it in tauri-docs regardless but not in the main repo.

**Comment by matthme** [comment]
Okay, makes sense. I'll make a (signed) PR to the main repo then.

**Comment by matthme** [comment]
https://github.com/tauri-apps/tauri/pull/5985

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
