### PR TITLE
chore: fix incorrect permissions

### PR DESCRIPTION
**Pull request by amrbashir**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content
- Changes to the docs site code
- Something else!

#### Description

- Closes # 
- What does this PR change? Give us a brief description. 
- Did you change something visual? A before/after screenshot can be helpful.

### CODE REVIEW

**Comment by vasfvitor** [comment]
@amrbashir these links seems to be breaking but I can't find out why, same has happened on another PR https://www.github.com/tauri-apps/tauri-docs/pull/2137 but it built locally. Oddly, another PR with same diff, didn't break

**Review by vasfvitor — APPROVED** [review]

**Comment by amrbashir** [comment]
I have no idea tbh 😅

**Comment by FabianLars** [comment]
i see the same error locally after cloning the repo from scratch

**Comment by FabianLars** [comment]
that was my bad 😩

**Pull request merged**
