### PR TITLE
docs(features): update Commands page

### PR DESCRIPTION
**Pull request by pewsheen**
#### What kind of changes does this PR include?

- New or updated content
  - Update `/features/commands/`

#### Description

- What does this PR change? Give us a brief description. 
  - Update `/features/commands/`

It's basically copied from 1.0 guide, let's see what we can improve it

### CODE REVIEW

**Comment by pewsheen** [comment]
Maybe we should also mention this https://beta.tauri.app/guides/plugins/develop-mobile/#adding-mobile-commands

**Comment by vasfvitor** [comment]
> Maybe we should also mention this https://beta.tauri.app/guides/plugins/develop-mobile/#adding-mobile-commands

I haven't played with mobile, do you happen to know if this is the default pattern to invoke from mobile? If so, I agree that it could be linked. What bothers me is that it's in the context of "Mobile Plugin Development", otoh, could be copied and adapted, but I'm not so sure about it

Maybe if this section (mobile commands) could be moved to a partial file and imported both in this guide and on plugin development? Only partially solves the issue of being in "Plugin development" context.

What do you think?

Note:
https://discord.com/channels/616186924390023171/662624589037436928/1219455566985035898

**Comment by pewsheen** [comment]
Hmm.. Ok, I have changed my mind lol
I think this guide should focus on "Frontend -> Rust", and the mobile plugin command is another direction.

**Comment by vasfvitor** [comment]
Where are we at this? I think it's ok, later we can revisit to maybe add a tauri specta tip when it releases stable to v2

**Comment by pewsheen** [comment]
> Where are we at this? I think it's ok, later we can revisit to maybe add a tauri specta tip when it releases stable to v2

I’m also ok with it. We can improve it later

**Review by vasfvitor — APPROVED** [review]

**Pull request merged**
