### PR TITLE
Fix `cargo-xwin` installing command may not work for Linux

### PR DESCRIPTION
**Pull request by FlysoftBeta**
Linking issue: https://github.com/tauri-apps/tauri/issues/7004

### CODE REVIEW

**Comment by lucasfernog** [comment]
@FabianLars should we actually add the error message here?

**Comment by FabianLars** [comment]
yes I think we should

**Comment by FlysoftBeta** [comment]
The error message is now added :)

**Review by FabianLars — COMMENTED** [review]
Thank you!

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
