### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by lorenzolewis**
- Removes custom doc component (was derived from old version of Docusaurus)
- Add custom `pagination_next` to getting started platform pages so they go to the correct page

### CODE REVIEW

**Comment by lorenzolewis** [comment]
Fixes #324

**Review by FabianLars — COMMENTED** [review]
Not sure how i feel about the Intro -> Linux -> Development flow. Otherwise lgtm

**Comment by lorenzolewis** [comment]
So thinking to possibly remove the next page button on the intro page? Since there's already a call to action at the bottom to each platform I guess

**Comment by FabianLars** [comment]
Yeah sounds better 👍

**Comment by lorenzolewis** [comment]
Alright, that should fix it. I'll let CI run to make sure nothing broken and then should be good.

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
