### PR TITLE
Better mobile CSS for index

### PR DESCRIPTION
**Pull request by lorenzolewis**

### CODE REVIEW

**Comment by FabianLars** [comment]
hmm idk the images in the "security" and "built on rust" cards look really weird when stretched:


grafik
grafik

**Comment by lorenzolewis** [comment]
Which browser are you using? Mine looks like this: image

**Comment by FabianLars** [comment]
Tested with firefox and vivaldi on mobile and firefox and edge on desktop (with mobile emulation)

**Comment by lorenzolewis** [comment]
_murmurs about Safari non-standard CSS implementation_

How about now?

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
