### PR TITLE
Fix sidecar docs link

### PR DESCRIPTION
**Pull request by simonhamp**
#### Description

Fixes a broken link

### CODE REVIEW

**Review by dreyfus92 — COMMENTED** [review]
Hey @simonhamp, thank you for taking the time in contributing to Tauri Docs, if you head to the end of the `mdx` [file](https://github.com/tauri-apps/tauri-docs/pull/2794/files#diff-b3b78148ff36d19daba1a1615a09e351229bb42e1ee29ed5648dfe1835b131bbR183-R187) you can find all the link refs and just add the missing trailing slash 😁

**Comment by simonhamp** [comment]
Nope... I'm getting this when I follow the link in Chrome. But when I add the slash (as per the link that the nav menu uses), I have no problem seeing the page

Screenshot 2024-10-04 at 18 51 16

**Comment by dreyfus92** [comment]
@vasfvitor have you noticed this problem?

**Comment by vasfvitor** [comment]
> @vasfvitor have you noticed this problem?

not personally, but we've been having issues with trailing slash around the docs and I haven't found a definitive fix, we've been manually updating our links but a few passed by. 

note that I can't reproduce it

for this situation I guess it should be just to add the trailing slash on the link at the of the mdx file

**Comment by simonhamp** [comment]
That's what this PR does 😉

**Pull request merged**
