### PR TITLE
fix: remove dollar signs from cmdline instructions, closes #454

### LINKED ISSUE #454: bash: $: command not found...
The shell/bash code snippets shouldn’t start with the prompt sign `$`, especially if there is this super practical <kbd>Copy</kbd> button.

```bash
$ sudo dnf install […]
```
To be replaced by:
```bash
sudo dnf install […]
```

This prompt may confuse beginners, and is less and less _everywhere_. 

Found in the [Getting Started page](https://github.com/tauri-apps/tauri-docs/blob/dev/docs/getting-started/setting-up-linux.md), might be found elsewhere.

I’m ready to do a merge request if you agree with the purpose of this issue.

### PR DESCRIPTION
**Pull request by FabianLars**
For reasons see https://github.com/tauri-apps/tauri-docs/issues/454

I'm not 100% happy _everywhere_ but it's still better than before imo.

Edit: Also, vs-code's format-on-save makes it harder to diff again :))

### CODE REVIEW

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
I like that you updated the todo comment 😂

**Comment by JonasKruckenberg** [comment]
Actually, I'd like to add these back, but maybe in a way where the dollar sign is ignored for copy-paste. 
Turns out the dollar sign is kinds important for syntax highlighting. But don't worry 👍🏻

**Comment by FabianLars** [comment]
Yeah same, but with docusaurus it looks like we need a) some weird css or b) a custom code block thingy and i wanted to get this PR out of the way for the icons&deps doc update.

**Comment by FabianLars** [comment]
But i don't see what you mean with the syntax highlighting thingy.
If i understood you correctly, then the actual problem is that we use `sh` instead of `bash` on the code blocks (only the latter seems to have highlighting).

**Comment by JonasKruckenberg** [comment]
Aaaactually, I learned from the rust book, that `console` as the code block lang gives you much nicer, more consistent syntax highlighting

**Comment by FabianLars** [comment]
doesn't seem to be supported by docusaurus / prism. So we may have to write our own prism lang definition for that one :/

**Pull request merged**
