### PR TITLE
v1-rc docs

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
This includes the reworked docs structure while keeping the old theme and landing page

### CODE REVIEW

**Comment by lorenzolewis** [comment]
Should this be opened against the v1 branch instead?

**Comment by lucasfernog** [comment]
I believe we're publishing this one for the RC instead of the v1 refactor since the style is not ready yet.

**Comment by lorenzolewis** [comment]
Got ya, been MIA between work and vacation so I'm all kinds of behind 😆

**Comment by FabianLars** [comment]
> since the style is not ready yet.

And more importantly we want v1 to be an even bigger "stunt" (somewhat of a quote from amr on discord :P )

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
