### PR TITLE
feat: plugin setup docs consistency, fix desktop & mobile only setup

### PR DESCRIPTION
**Pull request by lucasfernog**
- makes the setup docs consistent across all plugins
- adjust the manual installation steps for desktop or mobile only plugins

### CODE REVIEW

**Review by vasfvitor — APPROVED** [review]
great, minor note is that in some places we're using 
```
```sh frame=none
```
image


and others
```
```sh
```
image

so that's may be a consistency point we need to tackle, do you have an opinion on this? if anything, I can do it as it is just manual labor.

I'm now looking at the live preview, but so far so good

**Review by vasfvitor — COMMENTED** [review]
some plugins have the compatibility and minimum rust version listed. some not, about this there is this PR https://github.com/tauri-apps/tauri-docs/pull/1881 that it may well also fit the plugin minimum version (but still needs to be manually updated, at least in one place). 

Going further, join PluginLinks with the compatibility to create a PluginHeading

**Comment by lucasfernog** [comment]
we should really start merging PRs, second time I've touched something already covered somewhere else.

**Comment by lucasfernog** [comment]
ahh i see you only added the component and not the references, so i guess it's easier to manage this

**Comment by lucasfernog** [comment]
let's go with ` frame=none` for now, though the other one is just a side effect of using CommandTabs, which uses the Code component directly instead of triple ticks.

**Pull request merged**
