### PR TITLE
chore(deps): Update astro to v4

### PR DESCRIPTION
**Pull request by FabianLars**
Just wanna check if it fails to build here too as it does locally for me. Couldn't figure out the issue yet :/

### CODE REVIEW

**Comment by vasfvitor** [comment]
From what I gathered it's a compatibility issue between Starlight and starlight-blog plugin (I've tested and it is). It has to be first improved on Starlight then on plugin. The plugin's maintainer is already on it and opened a PR on Starlight

All details on Astro discord channel: https://discord.com/channels/830184174198718474/1070481941863878697/1181965518853394523
invite: https://astro.build/chat

**Comment by lorenzolewis** [comment]
I'm thinking about re-creating that blog functionality after I get past a few pieces of the API generators. There's some UX improvements with the page layouts that we could get and it would also unlock this update. But we'll see who's faster: me or Starlight 😅

**Comment by vasfvitor** [comment]
> I'm thinking about re-creating that blog functionality after I get past a few pieces of the API generators. There's some UX improvements with the page layouts that we could get and it would also unlock this update. But we'll see who's faster: me or Starlight 😅

If that's the case, wouldn't be better to just make a blog.tauri website? Speaking of which, is there a reason that the only website is the docs? Like, it could have a main page with blog, about and stuff, and then, docs in docs.tauri

**Comment by lorenzolewis** [comment]
Potentially, but that also means you need to maintain the same things in those respective places. If we have it all under one repo then it makes it a lot easier to keep everything updated by only needing to monitor one place. I do like other places that have it separate but I feel for us it's a better to call to bundle docs, blog posts, and "about" pages under one roof to be as easy to maintain as possible.

**Comment by simonhyll** [comment]
Resolved in #1858

**Pull request closed without merging**
