### PR TITLE
Sign Windows: singing → signing

### PR DESCRIPTION
**Pull request by tobyspark**
Corrects typo (in an area we really don’t want any typos, given it’s code signing and  typosquatting is a thing)

### CODE REVIEW

**Comment by FabianLars** [comment]
I have proofread the PR 3 times and didn't see this fml

**Comment by FabianLars** [comment]
but hey, nothing better than a singer you totally trust i guess

**Comment by tobyspark** [comment]
...the link was good, so it was just cosmetic. But yeah, nothing better, eh =]

**Comment by Levminer** [comment]
Wow, this is embarrassing 😂

**Pull request merged**
