### PR TITLE
Move images

### PR DESCRIPTION
**Pull request by lorenzolewis**
This moves images for the guides from `static` to be in their respective `guides` folders. This enables us to more easily run images through i18n.

No issues are known with this approach and it's supported as confirmed by Docusaurus: https://discord.com/channels/398180168688074762/867060369087922187/987282727084634152

### CODE REVIEW

**Review by JonasKruckenberg — DISMISSED** [review]

**Comment by JonasKruckenberg** [comment]
Let's wait for the preview though

**Comment by lorenzolewis** [comment]
Haha I was going to say, let's see if the build even works first :D

**Comment by lorenzolewis** [comment]
Ah, I think that was my fault because I'm testing against Crowdin right now as well

**Comment by JonasKruckenberg** [comment]
It does, in fact, not 😂

**Comment by lorenzolewis** [comment]
@JonasKruckenberg look good to you now?

**Comment by lorenzolewis** [comment]
Closes #663

**Comment by lorenzolewis** [comment]
@JonasKruckenberg give the deploy preview a look again when you have a chance. I think Netlify was just having some performance issues and that's why the page loading was slow. But dynamic dark/light isn't working still

**Comment by lorenzolewis** [comment]
Nope, I take it back. Will probably just ditch that whole plugin for now (will do later this weekend)

**Comment by lorenzolewis** [comment]
Could look at using this instead: https://docs.netlify.com/site-deploys/post-processing/

**Comment by lorenzolewis** [comment]
@JonasKruckenberg I enabled asset optimisation in Netlify and removed IdealImages. See any issues with this build?

**Comment by lorenzolewis** [comment]
Got this one in with https://github.com/tauri-apps/tauri-docs/pull/685

**Pull request closed without merging**
