### PR TITLE
Instructions for creating a flatpack

### PR DESCRIPTION
**Pull request by robertosw**
#### What kind of changes does this PR include?
- New or updated content

#### Description
- Reference: https://github.com/tauri-apps/tauri/discussions/4426#discussion-4162865
- What does this PR change?
  - I added a docs page that tells users how they can bundle their tauri application into a flatpak
- Did you change something visual? No

#### Open Questions
- Maybe adding some simple description of how flatpak works, might be good? 
- I have no experience publishing to flathub, a section for this would be nice
- ~How do I add this page to the navbar?~
- ~Why is the "On this page" not showing the headers?~

### CODE REVIEW

**Comment by FabianLars** [comment]
First of all, big thanks!

> Maybe adding some simple description of how flatpak works, might be good?

No idea what that section would entail tbh

> I have no experience publishing to flathub, a section for this would be nice

i thought that's what we were talking about, mb. But yeah, that's what most flatpak consumers will actually use so we for sure need it. It also doesn't really build on top of the standalone flatpak approach though so that will be a bit harder. That said, no need to add it in this PR, we can work on that in another one.

> How do I add this page to the navbar?

Remove the distribute.mdx file, create a new distribute folder and move the flatpak guide into that. It'll also need an index file like this one https://github.com/robertosw/tauri-docs/blob/flatpak-docs/src/content/docs/guides/debug/index.mdx - at least i assume that's the approach we wanna take for now, maybe Lorenzo will ~~scream at me~~ correct me later.

> Why is the "On this page" not showing the headers? 

Try changing `#` to `##`. There should only be one `#` per page and iirc that's set via the `title` property already.

**Comment by robertosw** [comment]
> Try changing `#` to `##`. There should only be one `#` per page and iirc that's set via the title property already.

This did the trick 👍🏼 

<br>

The "distribute" page is now in its own folder as a `index.mdx` that links the `flatpak.mdx` page with a button. The "Contribute" stub is still shown below that button, to indicate that this is not yet done.
https://deploy-preview-1760--tauri-docs-starlight.netlify.app/guides/distribute/

**Comment by robertosw** [comment]
Since this my page is not really about the distribution to flathub, should I move it to "build" instead of "distribute"? We could link against it later in the Distribute/Flatpak page

**Comment by robertosw** [comment]
I found this [guide](https://docs.flathub.org/docs/for-app-authors/submission/) on how to submit your flatpak to the Flathub repo. I linked this at the end of this flatpak page, because I think this already explains everything.
But still, most of the content of this page is about building the flatpak, but it would be silly to create a Distribute/Flatpak page that just contains "Yeah if everything from the Building/Flatpak page works, go look at this link".
How do we solve that? I'd think some people would still search for flatpaks in "Building" rather than "Distribute"

**Comment by FabianLars** [comment]
> I found this [guide](https://docs.flathub.org/docs/for-app-authors/submission/) on how to submit your flatpak to the Flathub repo. I linked this at the end of this flatpak page, because I think this already explains everything.

The guide isn't really clear imo. The first part kinda sounds like you could upload the generated .flatpak bundle (which your docs here create) which is not the case. This is only the testing phase. For uploading the app to flathub you only upload the manifest and build at least the flatpak bundle but preferebly the app itself too in their CI. Especially with Rust apps this is not exactly straight forward (also closed source vs open source apps) which this guide doesn't touch at all.

> But still, most of the content of this page is about building the flatpak, but it would be silly to create a Distribute/Flatpak page that just contains "Yeah if everything from the Building/Flatpak page works, go look at this link".
> How do we solve that? I'd think some people would still search for flatpaks in "Building" rather than "Distribute"

True true, but as said above we need an explicit flathub guide anyway. But yeah, we could move this part into the building sections to .deb and .appimage and only have the seperate flathub guide in distribute.
But Lorenzo also wanted to merge the 2 sections (was there a decision? @lorenzolewis) so i'm not sure either.

**Comment by robertosw** [comment]
Okay, fair enough 👍
I'd say I am done, because I cannot usefully contribute to the flathub guide (yet).
So this can be merged

**Comment by RoseBlume** [comment]
I made some last minute changes so it should be ready to merge. If you want to test the files they are already in the AUR under the names `rosary-tauri` and `rosary-git`

**Comment by RoseBlume** [comment]
I would like to help get this finished. Should I open a new pull request or is there a way to contribute to this one?

**Comment by FabianLars** [comment]
heh, good timing. I was also working on this today (not that much yet). We can merge it as a draft so you can work on it easier.

**Comment by FabianLars** [comment]
Alrighty, merged as a draft. Please reach out to me if you change your mind :)

**Comment by RoseBlume** [comment]
Ok, I've made a few improvements I just need you to look into it. 
[Instructions For Creating A Flatpak](https://github.com/tauri-apps/tauri-docs/pull/2277)

**Pull request merged**
