### PR TITLE
fix: Missing linux packages

### PR DESCRIPTION
**Pull request by akryptic**
#### What kind of changes does this PR include?

- New or updated content

#### Description
- Refer to this issue for further info: https://github.com/tauri-apps/tauri/issues/3701

### CODE REVIEW

**Comment by akryptic** [comment]
I noticed that the documentation was missing some important dependencies for Linux systems: javascriptcoregtk-4.1, libsoup-3.0, and webkit2gtk-4.1.

I've done my best to update the guide to include these dependencies. However, since I'm new to Linux and lack experience, I'd appreciate it if someone could double-check to ensure that these dependencies are available in the package lists of different distributions.

Thanks for your help!

**Comment by FabianLars** [comment]
Thanks for contributing :)
javascriptcore and libsoup are direct dependencies of webkitgtk so this should not be required. Do you still have the error messages or whatever made you look into this at hand to share with us?

**Comment by akryptic** [comment]
Here you go

```
The following warnings were emitted during compilation:

warning: soup3-sys@0.5.0: 

error: failed to run custom build command for `soup3-sys v0.5.0`

Caused by:
  process didn't exit successfully: `/mnt/Storage/dev/passguard/desktop/src-tauri/target/release/build/soup3-sys-784521f95e787e33/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBSOUP_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libsoup-3.0 libsoup-3.0 >= 3.0

  The system library `libsoup-3.0` required by crate `soup3-sys` was not found.
  The file `libsoup-3.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `libsoup-3.0.pc`.

warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: javascriptcore-rs-sys@1.1.1: 

error: failed to run custom build command for `javascriptcore-rs-sys v1.1.1`

Caused by:
  process didn't exit successfully: `/mnt/Storage/dev/passguard/desktop/src-tauri/target/release/build/javascriptcore-rs-sys-f03246449205d41c/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=JAVASCRIPTCOREGTK_4.1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags javascriptcoregtk-4.1 javascriptcoregtk-4.1 >= 2.38

  The system library `javascriptcoregtk-4.1` required by crate `javascriptcore-rs-sys` was not found.
  The file `javascriptcoregtk-4.1.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `javascriptcoregtk-4.1.pc`.

       Error failed to build app: failed to build app
```

**Comment by akryptic** [comment]
can confirm for debian based and arch based, cause recently (previous 3 days) got the same error on both distro
and installing those deps works.

Edit: This only affects tauri v2 , v1 works without needing these (or idk how but you don't have to install them seperately.)

**Comment by FabianLars** [comment]
hmm, i didn't see this on any of my machines or CI setups (yet) 🤔 Do you still have one system this error happens? Could you post the output of `tauri info` from that system (using v2 cli).

Also for what it's worth, v1 used different versions of webkitgtk, jsc and libsoup, so rerunning the new install command (with normally only the new webkitgtk version) is required and comparing v1 and v2 may not get us far idk.

**Comment by akryptic** [comment]
```[✘] Environment
    - OS: Ubuntu 22.04 X64
    ✘ webkit2gtk-4.1: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.11.1
    - pnpm: 8.15.4
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

Umm... I am not comparing :sweat_smile: Just telling what i observed , cause it can be helpfull sometime. 
BTW i reported this on the  discord server first and simon asked me if i can create PR to fix this :sweat_smile: IDK much

**Comment by FabianLars** [comment]
hmm, that output simply suggests that you never ran `sudo apt install libwebkit2gtk-4.1-dev` 🤔

**Comment by akryptic** [comment]
yeah, cause its fresh kubuntu installation and docs don't say to install it(`libwebkit2gtk-4.1-dev`) so why would i install it?
Also copy pasted all the commands from prerequisits, so no way i messed up there. Basically the point is what docs say don't works recently.

**Comment by FabianLars** [comment]
It does ask you to install it though

https://beta.tauri.app/guides/prerequisites/#linux
grafik

**Comment by akryptic** [comment]
> It does ask you to install it though
> 
> https://beta.tauri.app/guides/prerequisites/#linux grafik

Yeah, i know I followed exactly what it said, but faced the issue and to confirm this my friend also got the same error. and installing those dependencies worked.

**Comment by akryptic** [comment]
maybe have a look at this? 
https://github.com/tauri-apps/tauri/issues/3701#issuecomment-1499791223

**Comment by simonhyll** [comment]
Having issues verifying this atm, my dang VM's don't want to cooperate >.<

**Comment by simonhyll** [comment]
Finally VM wanted to cooperate

@ardentkilnfire I just did a completely fresh install of Kubuntu 22.04 LTS, using the minimal install option. Literally only ran the currently up dependencies command and installed Rustup, created a fresh Tauri project using the curl variant of CTA, and bam, works just fine
image

**Comment by akryptic** [comment]
Yeah, It's cause of follwing v1 instructions :expressionless: 

Thanks for your time guys

**Pull request closed without merging**
