### PR TITLE
Add Calciumdibromid to showcase

### PR DESCRIPTION
**Pull request by crapStone**

### CODE REVIEW

**Comment by nothingismagick** [comment]
@Laegel - this is great - I think we should however ONLY show projects that are 1.0+ 

what do you think?

**Comment by 6543** [comment]
it is at version v0.3.0 but it's already used & core function could be considered as v1 ;)

It's just some "nits" have to be done (refactor pdf generation ...) don't know if put a hard limit  1.0+ is good - but it's your choice anyway ...

**Comment by crapStone** [comment]
The 0.x is only because we wanted to wait for tauri beta (and an issue with PDF generation).
We have a webapp deployed that is already used by the students and i'll finish the migration to `tauri-beta` soon.

After that the only thing stopping us from a 1.0 release is a rewrite of the PDF generation in pure Rust and we will probably take the webapp down, or at least aggressively push the desktop app, because our server is overloaded XD.

If you still think that we should wait until we finished these points I will close this PR and open one after the 1.0 release.

**Comment by 6543** [comment]
@crapStone let them decide ...

**Comment by nothingismagick** [comment]
i guess - what I meant - and sorry if I was unclear, is that we should just showcase projects that use tauri 1.0.0 - this project absolutely belongs here. and seriously - PDF generation is such a massive thing, that would be an amazing contribution back to the community! ❤️

**Review by 6543 — APPROVED** [review]
nice - lgtm will not count, just ok from cabr2 side ;)

**Comment by nothingismagick** [comment]
I guess I assumed you wanted the world to know bout this ;)
https://github.com/Calciumdibromid/CaBr2/blob/14c1fe10f4b8897934af7229451636d97190441f/src-tauri/Cargo.toml#L32

**Comment by lucasfernog** [comment]
package.metadata.bundle isn't read anymore btw.

**Comment by crapStone** [comment]
i got the idea after the big conversation about Angular I started today on the Discord server and our team agreed to this :sweat_smile:

**Comment by crapStone** [comment]
> I guess I assumed you wanted the world to know bout this ;)
> https://github.com/Calciumdibromid/CaBr2/blob/14c1fe10f4b8897934af7229451636d97190441f/src-tauri/Cargo.toml#L32

If you are talking about the `api-all`: this was just a quick-fix because I couldn't find any documentation about the new format

**Comment by crapStone** [comment]
> package.metadata.bundle isn't read anymore btw.

so I should put all of this back into the `tauri.conf.json`?

**Comment by Laegel** [comment]
Awesome work @crapStone & @6543, we'll gladly accept this PR, of course!

@nothingismagick Remove Alpha Tauri projects? I guess we should if we don't want people to find outdated code, as it would be counter productive. But I'd like to let them at least a chance to upgrade to beta before removing them from the showcase!

**Comment by 6543** [comment]
well CaBr2 is **now** on **beta**

**Comment by Laegel** [comment]
Just one thing: either change `'cabr2/logo.png'` for `'cabr2/icon.png'` or rename "icon.png" for "logo.png".
And we should also find out why the website isn't building correctly for this PR. 
https://deploy-preview-201--tauri.netlify.app/en/

**Comment by crapStone** [comment]
@Laegel  sry, copy-paste-error XD

**Comment by crapStone** [comment]
We tried to build it locally and it only works when we remove one of the other showcases.
But I couldn't find any indication in the code to why this happens.

**Comment by 6543** [comment]
@nothingismagick @Laegel any idear where to look at, that can cause this bug?

**Comment by Laegel** [comment]
Yup sorry, my bad: it lacks a project description but the i18n solution is not good (WIP, got to switch to Docusaurus builtin system instead) and lacks explicitness on how to define it.
To fix it, open tauri-docs/translations/en.json, look for the `pages.showcase.projects` nested property then, on the 4th index, set your project description in a new object.

**Comment by Laegel** [comment]
@6543 @crapStone forgot to tag, cf my previous comment to fix the faulty build.

**Comment by crapStone** [comment]
@Laegel thanks, that fixed it

**Review by 6543 — APPROVED** [review]
did the job :)

**Pull request merged**
