### PR TITLE
Update setting-up-linux to include squashfs-tools

### PR DESCRIPTION
**Pull request by rockerBOO**
When making a container on ubuntu buster, squashfs-tools is required when making the AppImage.

I'm not familiar with most of these so please advise.

### CODE REVIEW

**Comment by lucasfernog** [comment]
We made some changes to the AppImage bundler when running on docker, can we wait for the RC to be published so you can try it again? If it's indeed needed we can merge this, but I didn't see this requirement when testing it.

**Comment by rockerBOO** [comment]
```
...
 Bundling ecogarden_0.1.0_amd64.deb
thread 'main' panicked at 'mksquashfs is not installed. Please install squashfs-tools and try again.: Os { code: 2, kind: NotFound, message: "No such file or directory"
}', /home/runner/work/binary-releases/binary-releases/tooling/bundler/src/bundle/appimage_bundle.rs:26:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 app:spawn Command "/builds/project-0/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 101 +1ms
```

I'm running through a gitlab-runner in a docker container. 

This is my config to run it. It runs fine if I add `squashfs-tools`

```
build-linux:
  image: rust:1-buster
  stage: build
  before_script:
    -
      apt update
    -
      apt install -y libwebkit2gtk-4.0-dev
      build-essential
      curl
      wget
      libssl-dev
      libgtk-3-dev
      libappindicator3-dev
      patchelf
      librsvg2-dev
    -
      curl -o-
      https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - \. "$NVM_DIR/nvm.sh"
    - nvm install node --latest-npm
    - nvm use node
    - corepack enable
  script:
    - yarn install --immutable
    - yarn workspace create install --immutable
    - yarn workspace create run build
    - yarn workspace create tauri build
```

I could try again when the RC is released though.

**Comment by lucasfernog** [comment]
What's your tauri CLI version?

**Comment by rockerBOO** [comment]
```
    "@tauri-apps/api": "^1.0.0-beta.8",
    "@tauri-apps/cli": "^1.0.0-beta.10",
```
I may need to sync these up.

**Comment by nothingismagick** [comment]
may also just wait for us to publish the 1.0.0-rc.0 and try again :)

**Comment by FabianLars** [comment]
Also, if you use yarn2/3 the caret (^) will make it resolve the package to `1.0.0-beta-rc.4` which may use the old appimage bundler implementation

**Comment by rockerBOO** [comment]
Ok looks like the package resolution was causing this to some degree. Took out the `^` and got a new error. 

```
    Finished release [optimized] target(s) in 5m 10s
    Bundling ecogarden_0.1.0_amd64.deb
    Bundling ecogarden_0.1.0_amd64.AppImage
Error: failed to bundle project

Caused by:
    Shell Scripting Error:`error running appimage.sh, try running with --verbose to see command output`

 app:spawn Command "/builds/project-0/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 1 +1ms
```

I'll wait for the RC and try again.

**Comment by lucasfernog** [comment]
Yeah the existing beta has an issue on docker, but we're just publishing `@tauri-apps/cli` now. Everything else has been released.

**Pull request closed without merging**
