### PR TITLE
Test Untrusted PR with Deploy

### PR DESCRIPTION
**Pull request by simonhyll**
Test

### CODE REVIEW

**Comment by lorenzolewis** [comment]
Just putting notes for myself here.

From what I can tell, GitHub tries to make a new environment for each action trigger TYPE
Screenshot 2022-07-08 at 22 42 17

I may just move the secrets over to repo secrets instead and it _should_ fix it

**Comment by FabianLars** [comment]
You could do it the ugly-ish way and check if it's a fork and skip all the crowdin stuff lol

Edit: Ahh the deploy itself would still fail i guess.

**Comment by lorenzolewis** [comment]
Could you rebase this again and see if it works now?

**Comment by lorenzolewis** [comment]
Tested outside of this and looks to be fixed, closing

**Pull request closed without merging**
