### PR TITLE
fix header overlap on mobile

### PR DESCRIPTION
**Pull request by mosheduminer**

### CODE REVIEW

**Comment by nklayman** [comment]
Fix works for me on a pixel 4, but the header is quite big now. Maybe in the future we should look at auto hiding and revealing on scroll.

**Comment by mosheduminer** [comment]
I agree with @nklayman, the the current setup of three levels of headers (in the docs) takes up a lot of precious vertical space.

**Comment by nklayman** [comment]
And for me on a 18:9 aspect ratio I have extra vertical space, for people on older 16:9 devices their vertical space is even more limited.

**Comment by mosheduminer** [comment]
@nklayman @Laegel what do you think of an implementation similar to the one here: https://css-tricks.com/styling-based-on-scroll-position/ ? I could add it to this PR, or make a separate one.

**Comment by mosheduminer** [comment]
I wrote some JS/CSS to hide the documentation navbar on scroll. I suppose that should go in a separate PR?

**Comment by nklayman** [comment]
Yeah, I'd make a separate PR for that, thanks for adding!

**Pull request closed without merging**
