### PR TITLE
Feat/index revision

### PR DESCRIPTION
**Pull request by lorenzolewis**
Would appreciate feedback on the design.

### CODE REVIEW

**Comment by FabianLars** [comment]
I don"t have much to say, i like it 👍 

Just one small problem, the get started button is misaligned on mobile:
grafik

**Comment by lorenzolewis** [comment]
Just need a bit of padding on the bottom, right?

**Review by lucasfernog — APPROVED** [review]
LGTM

**Comment by FabianLars** [comment]
> Just need a bit of padding on the bottom, right?

Yeah. on bigger screens `.hero` has top/bottom padding and on small screens it's set to 0

**Comment by lorenzolewis** [comment]
Fixed it

**Pull request merged**
