### PR TITLE
[i18n-ignore] Updated `src-tauri/capabilities/main.json` to `src-tauri/capabilities/default.json`

### PR DESCRIPTION
**Pull request by patelka2211**
#### Description

- What does this PR change? Give us a brief description. 

Updated `src-tauri/capabilities/main.json` to `src-tauri/capabilities/default.json` for the Security/Plugin permissions docs.

Does Tauri use `default.json` and `main.json` for different purposes? `default.json` is created by default, so I thought that maybe in stable releases, Tauri uses `default.json`.

Should I make this change to every instance?

### CODE REVIEW

**Comment by FabianLars** [comment]
> Does Tauri use default.json and main.json for different purposes? default.json is created by default

We may have changed the file name or just messed up the docs, but functionality wise the file name doesn't matter, tauri will read all json files in that directory by default.

Edit: If the templates use default.json then ig it makes sense to have the docs match that.

**Comment by patelka2211** [comment]
Thank you for the clarification, @FabianLars. Please let me know if you’d like me to update all instances of `main.json`. If not, I hope the changes I made [here](https://github.com/tauri-apps/tauri-docs/pull/2810/files#diff-ed9e30c72c213b61576fcb784d234b919396443a58dde10f05c2fd4704b5ddc5) are acceptable. Thanks!

**Comment by FabianLars** [comment]
Without knowing where we use main.json right now (i'm on my phone), I think that it makes sense to update all of them, yes.

**Comment by patelka2211** [comment]
Tauri template uses `default.json`. https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-cli/templates/app/src-tauri/capabilities/default.json

**Review by vasfvitor — APPROVED** [review]
thanks. I wonder how didn't the docs broke with those `"` missing that you fixed

**Pull request merged**
